name:                 port-matroid
version:              0.1.0.0
visibility:           public
id:                   port-matroid-0.1.0.0-inplace
key:                  port-matroid-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    Snapshot.Decode Snapshot.Encode Snapshot.Errors Snapshot.Limits
    Snapshot.Types

import-dirs:
    /root/port-matroid/dist-newstyle/build/x86_64-linux/ghc-9.0.2/port-matroid-0.1.0.0/build

library-dirs:
    /root/port-matroid/dist-newstyle/build/x86_64-linux/ghc-9.0.2/port-matroid-0.1.0.0/build

dynamic-library-dirs:
    /root/port-matroid/dist-newstyle/build/x86_64-linux/ghc-9.0.2/port-matroid-0.1.0.0/build

data-dir:             /root/port-matroid/.
hs-libraries:         HSport-matroid-0.1.0.0-inplace
depends:
    base-4.15.1.0 binary-0.8.8.0 bytestring-0.10.12.1
    containers-0.6.4.1
    cryptohash-sha256-0.11.102.1-8861a7f15a0b3374117e893cd12ce10a2c4a04f20236f7767cc31db12394ae53
    text-1.2.5.0 transformers-0.5.6.2
    unicode-transforms-0.4.0.1-7180efe9235e87d242514599f5352849a276a8130a4d4129b31c25cf252d62ff

haddock-interfaces:
    /root/port-matroid/dist-newstyle/build/x86_64-linux/ghc-9.0.2/port-matroid-0.1.0.0/doc/html/port-matroid/port-matroid.haddock

haddock-html:
    /root/port-matroid/dist-newstyle/build/x86_64-linux/ghc-9.0.2/port-matroid-0.1.0.0/doc/html/port-matroid
